- .evergreen.yml
- package.json
EVG-17439
This PR introduces a basic `.evergreen.yml` config for Parsley. It currently only tests two things, `compile` and `type_check`. We will add more tasks to the config as we introduce Storybook, Cypress, etc.
Tagging Sanjog because the ticket says to do so.
* This patch should pass!
> EVG-17439: Create base evergreen.yml config

- .eslintignore
- .eslintrc.js
- .evergreen.yml
- package.json
- src/.eslintrc.js
- src/App.tsx
- src/main.tsx
- vite.config.ts
- yarn.lock
EVG-17440
This PR configures ESLint and Prettier for Parsley.
Notable changes from Spruce:
* I omitted the `.prettierrc` file from Spruce. Everything in that file is actually set to the defaults, so the file doesn't really add anything to the default Prettier config.
* Organized and grouped rules together so that it's easier to see what rules are being disabled.
I'm on the fence about it, but I used the `airbnb` config because it has some stricter rules that are useful. We don't technically have to use it though. We could instead use `eslint:all / react:all` instead of `eslint:recommended / react:recommended` and then disable the rules we aren't interested in one by one.
It seems that ESLint eventually wants to move to a new file format called `eslint.config.js`. They are envisioning a …
> EVG-17440: Configure ESLint and Prettier

- src/components/LogRow/AnsiiRow/__snapshots__/AnsiiRow.stories.storyshot
- src/components/LogRow/BaseRow/index.tsx
- src/components/LogRow/ResmokeRow/__snapshots__/ResmokeRow.stories.storyshot
EVG-17677
Log lines are currently not always aligned due to log line numbers being able to have different lengths (e.g. `1` vs `99` vs `100`).
This PR sets a fixed width for the line number so that the log lines are always aligned at the same starting point.
- Manually looking 👀
> EVG-17677: Align log lines by setting fixed width for line number

- src/components/LogRow/AnsiiRow/AnsiiRow.stories.tsx
- src/components/LogRow/AnsiiRow/AnsiiRow.test.tsx
- src/components/LogRow/AnsiiRow/index.tsx
- src/components/LogRow/ResmokeRow/ResmokeRow.stories.tsx
- src/components/LogRow/ResmokeRow/ResmokeRow.test.tsx
- src/components/LogRow/ResmokeRow/index.tsx
- src/components/LogRow/RowRenderer/index.tsx
- src/components/LogRow/index.ts
- src/pages/index.tsx
EVG-17914
Our main bundle has gotten kind of big due to some dependencies that most users may not ever interact with. (LogUploader , Logs with AnsiiRow) So i thought it would make sense to split out those deps into their own bundles.
bundle before:
bundle after:
> EVG-17914 Add code splitting to produce smaller bundles

- src/utils/resmoke/helpers.test.ts
- src/utils/resmoke/helpers.ts
- src/utils/resmoke/index.ts
EVG-17539
Upon further investigation of resmoke lines i discovered mongod does not always separate the resmoke function with a pipe. So we need to add some further processing to separate the function.
example bad lines
> EVG-17539 Adjust resmoke function processing

- .evergreen.yml
EVG-17965 
Relocate attach results functions to `post` command. Evergreen stops running a task if one of its commands fail.
So it was never uploading any test results or artifacts for a failing test.
> EVG-17965 Ensure test results are attached

- src/components/LogRow/BaseRow/index.tsx
- src/components/LogRow/ResmokeRow/index.tsx
- src/utils/renderHtml/escapeHtml.ts
- src/utils/renderHtml/index.tsx
- src/utils/renderHtml/renderHtml.test.tsx
EVG-18081
Some resmoke lines often contain strings that resemble html characters. This is problematic when they are run through `parseHtml` since it will try to transform the string into an html element which does not exist. This PR adds a function called `escapeHtml`  which will replace any special characters with the ansii string representation. 
Added an allowlist to `parseHtml` i only enabled the tags we would expect to see this can be updated in the future.
No more console errors
Unit tests
> EVG-18081 Sanitize html characters for resmoke lines

- scripts/upload-bugsnag-sourcemaps.js
EVG-17545
Accidentally uploaded source maps and set the spruce url as the base instead of parsley
> EVG-17545 Use Parsley URL when uploading source maps

- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- src/components/LogPane/index.tsx
- src/components/LogRow/CollapsedRow/CollapsedRow.stories.tsx
- src/context/LogContext/index.tsx
EVG-18195
This PR removes the double scrollbar that was appearing in the `Y` direction. We were using `overflow` styling on the list container but we only really need `overflow-x` to enable horizontal scrolling.
Note that while there will no longer be two scrollbars, the scrollbars will still be visually different between mouse and trackpad. This is more a responsibility for the user, as they will need to change their scrolling settings to the following under General in System Preferences:
Perhaps we can put this in a FAQ somewhere, although it is a Mac specific setting.
- N/A
- Fixed stories which had been showing incorrect behavior when applying wrap and expanding rows.
- Update e2e tests
> EVG-18195: Fix duplicate scrollbar issue

- src/utils/filterLogs/filterLogs.test.ts
- src/utils/filterLogs/index.ts
EVG-18315
Expandable Rows should just hide the buttons instead of disabling filtering.
> EVG-18315 Hide expandable rows instead of removing filters

- src/pages/LogDrop/FileDropper.tsx
EVG-18414
Fixes a bug where uploads from using the file upload button would sometimes not be captured in parsley. 
https://user-images.githubusercontent.com/4605522/204870606-c45c77fc-6f92-4586-92bd-556b2151274e.mov
> EVG-18414 Fix bug preventing file upload button from working

- src/hooks/useFetch/index.ts
- src/hooks/useLogDownloader/index.ts
EVG-18358
Since we are awesome and handle the errors while fetching bugsnag doesn't automatically report the errors. So this adds some reporting. 
Broke some stuff
> EVG-18358 Report errors when fetching logs

- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- src/components/LogPane/index.tsx
EVG-18418
Adds a horizontal scrollbar for users with a mouse and no trackpad. 
Find a large log with a horizontal scroll and enable this option on a mac
> EVG-18418 Force horizontal scroll bar to appear

- src/utils/resmoke/helpers.test.ts
- src/utils/resmoke/helpers.ts
EVG-18441
Some logs featured negative timestamps which would not be detected by our regex this updates the offset regex to support it. 
Before:
After:
> EVG-18441 Handle timestamps with negative offsets

- src/components/LogRow/AnsiiRow/AnsiiRow.test.tsx
- src/components/LogRow/AnsiiRow/index.tsx
- src/components/LogRow/ResmokeRow/ResmokeRow.test.tsx
- src/components/LogRow/ResmokeRow/index.tsx
EVG-18375
This PR makes it so that we render rows that contain empty strings. The reason they were not being rendered before is because we were only checking if `lineContent` is falsy.
Maybe we can introduce an option when parsing the log to omit lines that only contain empty strings? We would need to know if users would actually find this helpful though.
- Added tests in `ResmokeRow.test.tsx`
- Added tests in `AnsiiRow.test.tsx`
> EVG-18375: Render rows that contain empty strings

- src/pages/LogView/LoadingPage/index.tsx
EVG-18442
Skip logkeeper metadata query if not a  resmoke build
> EVG-18442 Skip logkeeper metadata query if not a resmoke build

- cypress/integration/shortcuts.ts
- src/components/NavBar/index.tsx
- src/components/ShortcutModal/ShortcutModal.test.tsx
- src/components/ShortcutModal/index.tsx
- src/pages/index.tsx
EVG-18542
This PR adds an icon button in the `NavBar` which when clicked will open the `ShortcutModal`.
- In [EVG-18166](https://jira.mongodb.org/browse/EVG-18166), I'll do some more refactoring around the `NavBar` because it currently contains too much logic that is not related to the `NavBar` itself.
- Added tests in `shortcuts.ts` (Cypress)
> EVG-18542: Add icon button for shortcut modal

- src/context/LogContext/index.tsx
- src/test_utils/hooks.ts
EVG-18633
Introduces a `useEffectDebugger` hook which performs the same functionality as a useEffect but will also log the dependencies that have changed.
While investigating the above hook I realized we were processing log files twice due to an unstable dependency that was being re-initialized whenever the context would update.
> EVG-18633 Avoid processing log files twice

- src/components/Search/SearchBar/SearchBar.test.tsx
- src/components/Search/SearchBar/index.tsx
EVG-18534
This PR makes it so that using the Ctrl-F shortcut also selects any text that exists within the search bar.
https://user-images.githubusercontent.com/47064971/210426919-4daa0cc6-c247-4bed-87ed-c23cfcf272c1.mov
- Modified `SearchBar.test.tsx`
> EVG-18534: Select text content on Ctrl-F shortcut

- cypress.config.ts
- package.json
- yarn.lock
EVG-18656
There appears to be some sort of problem with the more recent versions of cypress and chrome. Long-running tests are OOMing and crashing when run locally. Taking a look at the memory usage of the cypress process the longer the test runs the more memory it uses until it crashes. Luckily there's a flag we can toggle to help out with this but we should keep an eye on the issue for future cypress releases.
https://github.com/cypress-io/cypress/issues/21135
https://github.com/cypress-io/cypress/issues/23391
https://github.com/cypress-io/cypress/issues/24905 
Also updates cypress for good measure https://docs.cypress.io/guides/references/changelog#12-3-0 
Cypress Memory usage
Before:
https://user-images.githubusercontent.com/4605522/210657670-3a45a3a3-6bee-4641-ab74-23d97a1d449e.mov …
> EVG-18656 Fix OOM when running long running cypress tests locally

- src/constants/logURLTemplates.ts
EVG-18666
Agent logs expect the letter E instead of A to be passed into the param.
https://github.com/evergreen-ci/evergreen/blob/24b4506727504198dd5cbbd47fb020c3e7e0a89a/rest/model/task.go#L321
Parsley beta link with above changes:
https://parsley-beta.corp.mongodb.com/evergreen/mongodb_mongo_master_enterprise_rhel_80_64_bit_dynamic_replica_sets_reconfig_jscore_stepdown_passthrough_4_linux_enterprise_8fd187d1f0c32a4d2fbf720e7f8c37b392c013b2_23_01_06_09_09_16/0/agent?bookmarks=0,258
> EVG-18666 Fetch agent logs correctly

- src/components/LogRow/CollapsedRow/CollapsedRow.test.tsx
- src/components/LogRow/CollapsedRow/index.tsx
- src/utils/expandedLines/expandedLines.test.ts
- src/utils/expandedLines/index.ts
EVG-18397
This PR makes it so the `Expand 5 Above and Below` button is always enabled. It also modifies `mergeIntervals` function to be slightly more robust.
- Added test in `utils/expandedLines/expandedLines.test.ts`
> EVG-18397: Always enable Expand 5 button

- cypress.config.ts
- cypress/integration/ansiiLogs/ansii_filtering.ts
- cypress/integration/ansiiLogs/ansii_highlighting.ts
- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/ansiiLogs/ansii_searching.ts
- cypress/integration/externalLinks.ts
- cypress/integration/resmokeLogs/resmoke_filtering.ts
- cypress/integration/resmokeLogs/resmoke_highlighting.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- cypress/integration/resmokeLogs/resmoke_searching.ts
- cypress/integration/uploadedLogs/upload.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- src/components/LogRow/AnsiiRow/__snapshots__/AnsiiRow.stories.storyshot
- src/components/LogRow/BaseRow/index.tsx
- src/components/LogRow/ResmokeRow/__snapshots__/ResmokeRow.stories.storyshot
EVG-18681
This PR enables Cypress test isolation, and modifies the tests so that they pass under this new setting.
I also used a smaller log file for the `resmoke_filtering.ts` file because the current one being used was taking 4 minutes in CI.
- Running the tests takes longer now (4 minutes as opposed to 3 minutes, according to the Cypress dashboard).
- It's possible to run Cypress tests independently now i.e. you don't need to pre-run tests before you run the test of interest.
- No visible changes
- Modified various tests in `cypress/integration` folder
- Used a smaller log file for `resmoke_filtering.ts`
> EVG-18681: Enable test isolation in Cypress

- src/pages/LogView/LoadingPage/index.tsx
EVG-18491
This PR fixes the laggy animation when loading a large log file on Chrome. Initially I (incorrectly) thought we might have to move the log processing off of the main thread, but then I noticed how the animation wouldn't lag at all on Safari but would perform pretty terribly on Chrome.
I think what's happening is that Chrome doesn't handle animating SVGs well (the Parsley icon gets rendered as an SVG.) Wrapping the SVG in a `div` and applying the animation on the `div` got rid of the lag.
(On Chrome)
https://user-images.githubusercontent.com/47064971/213779971-05a4d467-b197-4667-8694-b67135840129.mov
- Manually looking
> EVG-18491: Fix laggy loading animation on Chrome

- cypress/integration/ansiiLogs/ansii_filtering.ts
- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_filtering.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- cypress/integration/routes.ts
- src/components/BookmarksBar/BookmarksBar.test.tsx
- src/components/BookmarksBar/index.tsx
- src/components/LogPane/index.tsx
- src/components/LogRow/AnsiiRow/AnsiiRow.test.tsx
- src/components/LogRow/AnsiiRow/__snapshots__/AnsiiRow.stories.storyshot
- src/components/LogRow/BaseRow/Row.test.tsx
- src/components/LogRow/BaseRow/index.tsx
- src/components/LogRow/ResmokeRow/ResmokeRow.test.tsx
- src/components/LogRow/ResmokeRow/__snapshots__/ResmokeRow.stories.storyshot
- src/constants/queryParams.ts
- src/context/LogContext/index.tsx
- src/utils/filterLogs/filterLogs.test.ts
- src/utils/filterLogs/index.ts
EVG-18680
This PR makes it so that the `selectedLine` param is replaced with the `shareLine` param. `shareLine` is a better name for this query param because it makes it clear what it does.
I opened [EVG-18748](https://jira.mongodb.org/browse/EVG-18748) to delete the code around `selectedLine` at a later date.
- No visible changes.
- Added test in `routes.ts` (Cypress)
This ticket also includes updating the links in Evergreen [here](https://github.com/evergreen-ci/evergreen/blob/main/model/task/task.go#L483-L486). However, this PR will need to be merged and deployed **_before_** that change is made.
> EVG-18680: Replace selectedLine with shareLine param

- config/jest/setupTests.ts
- jest.config.js
- src/components/ErrorBoundary/index.tsx
- src/components/NavBar/UploadLink/UploadLink.test.tsx
- src/components/Search/SearchBar/SearchBar.stories.tsx
- src/context/toast/toast.test.tsx
EVG-18162
This PR mocks out some `console` logging to help our Jest tests be less noisy. `console.debug` and `console.error` are ignored completely, while `console.log` only ignores analytics events. This is to help catch stray `console.log` statements that may have been used while working on a ticket.
Other things:
- Fixed `UploadLink.test.tsx` because it was throwing a warning.
- Removed `defaultValue` from `Searchbar` story ([link](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args))
- Ran the Jest tests and looked at the output
> EVG-18162: Mock out console in Jest tests

- .evergreen.yml
- README.md
- cypress.config.ts
- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- package.json
- scripts/bootstrap-logkeeper.sh
- src/components/DetailsMenu/ButtonRow/index.tsx
- src/utils/string/index.ts
- yarn.lock
EVG-18664
- OOM errors appear to have gone away for now, but [v12.4.0 added](https://docs.cypress.io/guides/references/changelog#12-4-0) an `experimentalMemoryManagement` flag that we can introduce if they pop up again
- Electron browser no longer requires enabling clipboard permissions
- Update `copyToClipboard` function since [`writeText()` is  async](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText)
> EVG-18664: Use Electron browser with Cypress

- src/components/ErrorBoundary/index.tsx
EVG-18872
This PR leaves a breadcrumb on the error page. The breadcrumb will inform us if a user has seen the error page or not.
I put the breadcrumb in `componentDidCatch` based on this page about error boundaries ([link](https://reactjs.org/docs/error-boundaries.html)):
Note that I don't think you can see `console.debug` in Chrome by default (have to turn on verbose logging level).
- Tested manually by throwing error when accessing a value that didn't exist (e.g. `filters[2].caseSensitive`) and checked that the message was console logged
> EVG-18872: Leave breadcrumb on error page

- package.json
- src/components/ShortcutModal/index.tsx
- yarn.lock
EVG-18650
This PR upgrades the Modal to v14.0.1 Changes include:
* Updates Modal for dark mode brand refresh. (v13)
* Modal now accepts a forwarded ref. In addition, it respects an `id` when the prop is set, rather than overwriting the value internally. (v14)
- Clicked around and checked that things looked ok
> EVG-18650: Upgrade Modal to v14.0.1

- scripts/prepare-shell.sh
- I noticed that `pushd` and `popd` were failing in the script... then I noticed that we don't need to `cd` anywhere to run this command 😁
> Ubuntu upgrade cleanup

- docs/decisions/README.md
- docs/decisions/adr.md.template
EVG-19026
Creates a template for ADR's following @bsamek's format established in https://github.com/evergreen-ci/pine/tree/main/docs/decisions 
https://adr.github.io/
> EVG-19026 Create ADR template

- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- cypress/support/commands.ts
- package.json
- src/components/DetailsMenu/ButtonRow/ButtonRow.test.tsx
- src/components/DetailsMenu/ButtonRow/index.tsx
- src/components/DetailsMenu/__snapshots__/DetailsMenu.stories.storyshot
- src/components/LogRow/CollapsedRow/CollapsedRow.test.tsx
- src/components/PopoverButton/__snapshots__/PopoverButton.stories.storyshot
- src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/FilterGroup.test.tsx
- yarn.lock
EVG-18944
- Changes in https://github.com/mongodb/leafygreen-ui/pull/1611 mean that we don't need to use wrappers around buttons that function as tooltip triggers. Previously the wrapper was required or else a disabled button would block tooltip rendering.
- The package changes also mean that we need to check for the `aria-disabled` attribute instead of just using Cypress/React Testing Library's "disabled" check. There are some details [here](https://github.com/mongodb/leafygreen-ui/pull/1611#discussion_r1099090020).
- Update tests
> EVG-18944: Upgrade button

- docs/Highlighting,-Bookmarking-and-sharing.md
- docs/Home.md
- docs/Interface.md
- docs/Keyboard-Shortcuts.md
- docs/Local-Logs.md
- docs/Navigating-to-other-pages..md
- docs/Searching-and-filtering.md
Now that we are using ADRs in docs/decisions, unifying all docs in the docs/ directory makes them easier to see, both in the repo and in docusaurus.
> EVG-19038 Copy wiki to docs/ directory

- package.json
EVG-19051
Use the same command name for running local prod
> EVG-19051 Rename yarn prod command to be consistent with spruce 

- src/gql/generated/types.ts
- src/hooks/useQueryParam/index.ts
- src/utils/query-string/index.ts
- src/utils/query-string/query-string.test.ts
EVG-19304
Eliminates a render caused by `parseQueryString(searchParams.toString())` returning a new reference each time.
Incorporates changes to stringifyQuery introduced in https://github.com/evergreen-ci/spruce/pull/1766
> EVG-19304 Memoize useQueryParams return value

- src/analytics/addPageAction.ts
- src/analytics/loadingPage/useLogDownloadAnalytics.ts
- src/analytics/logDrop/useLogDropAnalytics.ts
- src/analytics/logWindow/useLogWindowAnalytics.ts
- src/analytics/preferences/usePreferencesAnalytics.ts
- src/analytics/shortcuts/useShortcutAnalytics.ts
- src/analytics/useAnalyticsRoot.ts
EVG-19318
While working on #233 I noticed that components were rerendering due to `sendEvent` being initialized on each render. Added some memoization to the analytics hooks to prevent these rerenders. This eliminates one render 
Waiting on #249
> EVG-19318 Memoize analytics hooks

- jest.config.js
- package.json
- src/gql/generated/types.ts
- src/utils/query-string/index.ts
- yarn.lock
EVG-18675
This PR upgrades the `query-string` package. I had to tweak the Jest configuration because the package was converted to pure ESM which I guess Jest doesn't like... Also, it's mandatory to call `queryString.parse` or `queryString.stringify` now.
- Existing tests should pass
> EVG-18675: Upgrade query-string to v8.1.0

- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- src/components/LogPane/index.tsx
- src/components/PaginatedVirtualList/index.tsx
- src/constants/keys.ts
EVG-18990
Since we are using a paginated list for the log view using the Home and End button would not take you to the top and bottom of the list. This PR overrides the default behavior and uses the scrollToLine function to jump automatically to the first and last line even if the view is paginated. 
Before:
https://user-images.githubusercontent.com/4605522/230675781-b80dfba5-03fd-437c-8422-ce9ddfe6ad29.mov
After:
https://user-images.githubusercontent.com/4605522/230675772-eec8340f-bfce-4f8e-86df-b9477109655a.mov
Lower paginationThreshold and use Home and End button to jump to parts of the log
> EVG-18990 Override Home and End button functionality in Paginated view

- src/components/SubHeader/EvergreenTaskSubHeader.tsx
EVG-19608
- Trim task names and show tooltip to prevent overflow. Since the task breadcrumb includes a badge, the trimming is handled outside of the breadcrumb component
- View a trimmed task using `yarn prod` at http://localhost:5173/resmoke/5d885fa3b5ca3eefec3fff6e3b0e559d/test/1753d455e14b437e0d5661fee23aab85?bookmarks=0,3603&shareLine=0
> EVG-19608: Trim task names

- package.json
- yarn.lock
EVG-19604
29.1.0 now supports typescript 5.0
https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md
> EVG-19604 Bump ts-jest to support typescript 5.0

- src/constants/logs.ts
- src/hooks/useLogDownloader/index.ts
- src/hooks/useLogDownloader/useLogDownloader.test.ts
- src/utils/fetchLogFile/fetchLogFile.test.ts
- src/utils/fetchLogFile/index.ts
EVG-19623
* Limits the maximum file size to 2.5 GB
* Ensures we still show a log if the server cancels the request
https://user-images.githubusercontent.com/4605522/232575596-f79451d3-36a3-4b33-8277-a20f540d7a90.mov
Update the `downloadSizeLimit` to be a size small enough that you can test against local data
Set the browser tab to offline to mimic the request being closed by the load balancer.
> EVG-19623 Limit streamed log file download size

- cypress/integration/ansiiLogs/ansii_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
EVG-18993
Looks like the test flakes from #252 were flakier than I thought. They passed twice on the pr but flaked after merging into main. This PR should fix the flakes. 
I ran the e2e tests 8 times in this patch to validate that they don't flake anymore.
https://spruce.mongodb.com/version/6446d030c9ec444826a0d3ff/tasks
> EVG-18993 Fix flaky virtualization cypress tests

- src/components/LogRow/CollapsedRow/CollapsedRow.test.tsx
- src/components/LogRow/CollapsedRow/__snapshots__/CollapsedRow.stories.storyshot
- src/components/LogRow/CollapsedRow/index.tsx
- src/gql/generated/types.ts
EVG-19008
This PR updates the collapsed row according to Lara's designs in Figma. 
Notable changes:
* Text style is `Body`, not`Overline`
* Expand icon is vertical, not diagonal
* Row is thicker. Kind of nervous about this one! 🧍
- Tests should pass
> EVG-19008: Implement collapsed row redesign

- .evergreen.yml
[EVG-18898](https://jira.mongodb.org/browse/EVG-18898)
Same idea as https://github.com/evergreen-ci/spruce/pull/1844. This will upgrade the db to be in sync with evergreen's post https://github.com/evergreen-ci/evergreen/pull/6542. Also upgrade to ubuntu22.04. We're all clear to upgrade the go version as well but that's not here since it's configured by a project variable.
N/A
Made [a patch](https://spruce.mongodb.com/version/646e64a30305b9ddaa5b762a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to test with the evergreen changes as a module (since this PRs test's won't have them).
https://github.com/evergreen-ci/evergreen/pull/6542
> EVG-18898 upgrade mongo db version

- src/components/ProjectFiltersModal/index.tsx
- src/gql/generated/types.ts
EVG-20341
This PR fixes a small problem where we shouldn't just check if `parsleyFilters` is null, we should also check if the length is 0 to show the "no filters available" message.
> EVG-20341: Fix condition for displaying project filters

- src/components/LogRow/AnsiiRow/__snapshots__/AnsiiRow.stories.storyshot
- src/components/LogRow/BaseRow/index.tsx
- src/components/LogRow/ResmokeRow/__snapshots__/ResmokeRow.stories.storyshot
EVG-20172
This PR makes the share icon position fixed (next to the line number). Also moved the icon to the right a bit.
> EVG-20172: Fix position of share icon

- src/components/PaginatedVirtualList/usePaginatedVirtualList.test.ts
- src/components/PaginatedVirtualList/usePaginatedVirtualList.ts
- src/components/PaginatedVirtualList/utils.ts
- src/gql/generated/types.ts
EVG-19861
- A crash was occurring when a user introduced a change (via filter, etc.) that caused the row count to be less than the max page size while not on the zeroth page. This led to the page size being calculated as a negative number.
- When this occurs, return the row count as the total page size and reset the page index to 0.
- Added unit test that currently fails on `main`
> EVG-19861: Fix filter crash bug

- src/gql/generated/types.ts
- src/gql/queries/get-test-log-url.graphql
EVG-20443
Arjun added an update to resolve Evergreen test log URLs via GQL when possible in https://github.com/evergreen-ci/parsley/pull/343. We need to further specify to exclude display names when filtering on a test name regex since the test results service's filtering functionality favors display names by default and these are not necessarily unique. 
I was able to confirm with evergreen and parsley staging that this query successfully fetches (and thus enables loading) the test result log URL when passed the unique test name (rather than display test name).
Must be deployed after https://github.com/evergreen-ci/evergreen/pull/6839.
> EVG-20443: set "excludeDisplayNames" flag in TestLogURL query

- cypress/integration/ansiiLogs/ansii_highlighting.ts
- src/components/LogRow/BaseRow/Highlighter.test.tsx
- src/components/LogRow/BaseRow/Highlighter.tsx
- src/components/LogRow/BaseRow/Row.test.tsx
- src/components/LogRow/BaseRow/index.tsx
- src/components/LogRow/RowRenderer/index.tsx
- src/gql/generated/types.ts
- src/utils/escapeTags/escapeTags.test.ts
- src/utils/escapeTags/index.ts
- src/utils/highlightHtml/highlightHtml.test.tsx
- src/utils/highlightHtml/highlighter.test.tsx
- src/utils/highlightHtml/highlighter.ts
- src/utils/highlightHtml/index.tsx
- src/utils/regex/index.ts
- src/utils/renderHtml/index.tsx
- src/utils/renderHtml/renderHtml.test.tsx
EVG-18978
This PR moves the highlight logic into the HTML parser to prevent highlights from corrupting HTML tags.
This approach solves a number of bugs in production including:
* Highlights can mess up log lines that include `<` and `>` since they are escaped to `&gt;` and `&lt;` respectively.
Correct line      |  Incorrect line after searching for `g`
:-------------------------:|:-------------------------:
* Searching for something like `span` will corrupt the `span` tags added via `ansi_to_html`.
Correct line      |  Incorrect line after searching for `span`
:-------------------------:|:-------------------------:
* Inconsistencies between searching and highlighting because of escaped vs unescaped text.
Search works, but missing highlight    |  Highlight works, but the search term needs …
> EVG-18978: Prevent highlights from corrupting HTML tags

- .github/dependabot.yml
EVG-20601
Following up from the UI round table and updating Dependabot to only trigger once a week. 3 per repo should be a nice balance while not being overwhelming for whoever is on call.
> EVG-20601 Update dependabot frequency to once a week

- .evergreen.yml
- src/gql/generated/types.ts
EVG-20617
Following up on our conversation this should reduce unnecessary uploads to the Cypress cloud service.
> EVG-20617 Only upload to cypress if on a pr, patch or mainline commit

- cypress/integration/routes.ts
- src/constants/queryParams.ts
- src/context/LogContext/index.tsx
EVG-18748
Stop supporting `selectedLine` query param in Parsley URLs now that the TTL has been reached.
- Remove tests for redirect support
> EVG-18748: Remove selectedLine redirect

- src/utils/file/index.ts
EVG-20175
This part of the code ends up calling `controller.close()` two times, because when it breaks out of the loop it also calls `controller.close()`. I just removed the extra call.
Also added a breadcrumb. (Which will get Sentry-fied in [EVG-20825](https://jira.mongodb.org/browse/EVG-20825))
- Manual testing. Set the file limit to something low (like 2) and uploaded a file and made sure the error went away.
> EVG-20175: Avoid calling controller.close() twice

- src/analytics/useAnalyticAttributes.ts
EVG-20863
Adds `userId` as a custom attribute in NewRelic. Will be used to provide Will's design project with more analytics.
- Cannot test as we do not have a staging environment for Parsley NewRelic but all I did was copy and paste from Spruce 👀
> EVG-20863: Add userId as custom attribute in New Relic

- src/components/ProjectFiltersModal/ProjectFilter.tsx
- src/components/ProjectFiltersModal/index.tsx
- src/components/ProjectFiltersModal/state.ts
- src/components/Search/index.tsx
- src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/FilterGroup.test.tsx
- src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx
- src/components/SidePanel/NavGroup/FilterNavGroup/index.tsx
- src/hooks/useFilterParam/useFilterParam.test.tsx
- src/types/logs.ts
- src/utils/matchingLines/index.ts
- src/utils/matchingLines/matchingLines.test.ts
- src/utils/query-string/index.ts
- src/utils/query-string/query-string.test.ts
EVG-20176
Renames the usage of the word "name" to "expression" in the context of Filters. This should free up that variable for when we start creating named filters.
Existing tests should suffice
> EVG-20176 Rename filter name attribute to expression

- package.json
- yarn.lock
EVG-20974
- `yarn dev` is broken locally due to [this syntax error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_name_after_dot_operator?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) included in the graphql package. Reverting the upgrade in https://github.com/evergreen-ci/parsley/pull/386 fixes it.
- I do not know why this package works fine in Spruce 🤔 but would rather figure that out separately
- `yarn dev` runs locally
> EVG-20974: Downgrade graphql dependency

- .evergreen.yml
EVG-21000
The [deploy task](https://spruce.mongodb.com/task/parsley_ubuntu2204_small_deploy_prod__v1.0.112_23_10_02_15_37_26) started OOMing in the ubuntu small distro so it likely needs to be on a bigger distro with more memory.
> EVG-21000 Move deploy to prod to ubuntu2204 large

- .evergreen.yml
EVG-21093
Noticed logkeeper logs were being uploaded with the wrong mime type
> EVG-21093 Use correct content_type type for logkeeper logs

- .evergreen.yml
[DEVPROD-1717](https://jira.mongodb.org/browse/DEVPROD-1717)
Upgrade the db to 7.0 in tests in advance of upgrading the db itself. Upgrade mongosh while we're at it.
https://github.com/evergreen-ci/evergreen/pull/7198
> DEVPROD-1717 upgrade mongo to 7.0

- src/hooks/useLogDownloader/index.ts
DEVPROD-2232
Since these alerts have been pretty noisy, let's log them as a warning and follow up by adjusting the alerting criteria in sentry in case they spike.
> DEVPROD-2232 Log download error at lower severity

- config/jest/setupTests.ts
- cypress/integration/routes.ts
- src/constants/logURLTemplates.ts
- src/gql/generated/types.ts
- src/gql/queries/get-task.graphql
- src/hooks/useLogDownloader/index.ts
- src/hooks/useLogDownloader/useLogDownloader.test.ts
- src/hooks/useTaskQuery/index.ts
- src/pages/LogView/LoadingPage/index.tsx
- src/pages/LogView/LoadingPage/useResolveLogURL.test.tsx
- src/pages/LogView/LoadingPage/useResolveLogURL.ts
- src/test_data/task.ts
Reverts evergreen-ci/parsley#431
Reverting due to spike in errors, see #evergreen-ops channel. Not quite sure what the problem is — maybe something with `abortController` which is only defined in production?
> Revert "DEVPROD-929: Use task log links from API"

- cypress/integration/ansiLogs/ansi_logView.ts
- cypress/integration/resmokeLogs/resmoke_logView.ts
- cypress/support/commands.ts
- cypress/support/index.ts
- cypress/tsconfig.json
- package.json
- src/components/LogRow/AnsiRow/index.tsx
- src/gql/generated/types.ts
- src/utils/string/index.ts
- src/utils/string/string.test.ts
- yarn.lock
DEVPROD-1904
The test flake here seems to have been caused by an assertion that would sometimes race with the click because it wasn't checking if the element existed.
There were also some silent uncaught exceptions that were caused by clicking on a copy to clipboard button because the cypress click event isn't a real click and the browser prevents copying to the clipboard without a real user interaction. 
It also looks like the actual copy assertions themselves weren't being resolved during the test and would leak into the next test run causing unpredictable behavior. I moved the the copy assertion to a util function and added a wait to ensure it gets run before the test completes
> DEVPROD-1904 Fix flaky test caused by racing assertions and Introduce realClick for clipboard events

- src/components/NavBar/index.tsx
- src/constants/externalLinks.ts
DEVPROD-821
- Rename `Wiki` ➡️ `Documentation`
> DEVPROD-821: Rename wiki navbar link

- src/components/BookmarksBar/__snapshots__/BookmarksBar.stories.storyshot
- src/components/BookmarksBar/index.tsx
- src/gql/generated/types.ts
DEVPROD-921
- Ensure width of bookmarks bar fits contents
> DEVPROD-921: Don't overflow bookmark bar

- cypress/integration/resmokeLogs/resmoke_logView.ts
DEVPROD-3178
I broke this by accident 🫠 This test has been flaking on & off since November so I assumed it was a flaky test and didn’t realize it was broken.
(Also the test is still flaky so it will still fail sometimes, but this was pre-existing behavior. It just won't fail 100% of the time now)
> DEVPROD-3178: Fix test in resmoke_logView.ts

- scripts/deploy/deploy.sh
DEVPROD-5097
The `deploy-prod` task succeeds even if this command fails. We should error and exit on failure.
Important note: We use `dist` folder, not `build` folder, in Parsley.
> DEVPROD-5097: Prevent deploy-prod task from failing silently

- .evergreen.yml
DEVPROD-787
Copied changes from evergreen-ci/spruce/pull/2281.
- [Patch](https://spruce.mongodb.com/task/parsley_ubuntu2204_small_lint_patch_0dda172225f653b5c3f511a8438b2e3f675cb264_65e22e09c9ec44d9ba8af418_24_03_01_19_35_46/logs?execution=0) which shows printed messages
> DEVPROD-787: Retry Node installation on CI

- .yarnrc
- scripts/deploy/utils/git/tag/constants.ts
- scripts/deploy/utils/git/tag/tag-utils.ts
- scripts/push-version.sh
DEVPROD-5132
Duplicates https://github.com/evergreen-ci/spruce/pull/2282
Updated git tag tracking definitions:
Will delete existing definition upon merge.
> DEVPROD-5132: Make tags unique

- .evergreen.yml
- src/gql/generated/types.ts
DEVPROD-5665
irt the slack thread we will no longer be sending data to cypress cloud. 
The associated task still displays all of the necessary logs and links to files in the files tab
> DEVPROD-5665 Update cypress e2e task to not report to cypress cloud

- package.json
- src/gql/generated/types.ts
- yarn.lock
DEVPROD-5759
- Upgrade Parsley to same GraphQL version as Spruce ahead of monorepo merge
- Verified in sandbox monorepo that this upgrade is necessary for GraphQL linting to work properly
> DEVPROD-5759: Upgrade GraphQL
