.evergreen.yml, LICENSE, cypress.config.ts
=> EVG-17447 Add Apache license and init cypress dashboard

package.json, src/App.tsx, src/context/GlobalProviders.tsx, src/context/LogContext/LogContext.test.tsx, src/context/LogContext/index.tsx, src/context/LogContext/state.ts, src/context/index.ts, yarn.lock
EVG-17511
Creates a simple context that exposes a hook to ingest and clear log lines
No visible changes
Wrote unit tests
=> EVG-17511 Create react context that stores log lines and wraps app

package.json, src/components/SearchBar/__snapshots__/SearchBar.stories.storyshot, yarn.lock
EVG-17624
Small bug fix for leafygreen select
=> EVG-17624 Bump @leafygreen-ui/select@7.0.1

.evergreen.yml
EVG-17686
Set up code to run local-evergreen on CI
=> EVG-17686 run local-evergreen server

.evergreen.yml, README.md
EVG-17619
Tries to start logkeeper on CI
There is a logkeeper  file in the task artifacts showing logkeepers log output.
=> EVG-17619 Setup logkeeper instance

src/components/LogRow/RowRenderer/index.tsx
EVG-17931
Cell Renderer seems to have some issues rendering lazy loaded components so for now i'm going to disable it.
=> EVG-17931 Remove lazy loading for AnsiiRow

.storybook/preview.tsx, cypress/integration/ansiiLogs/ansii_logView.ts, cypress/integration/resmokeLogs/resmoke_logView.ts, cypress/support/commands.ts, cypress/support/index.ts, src/components/DetailsOverlay/ButtonRow/ButtonRow.test.tsx, src/components/DetailsOverlay/ButtonRow/index.tsx, src/components/DetailsOverlay/DetailsOverlay.stories.tsx, src/components/DetailsOverlay/__snapshots__/DetailsOverlay.stories.storyshot, src/components/LogRow/AnsiiRow/AnsiiRow.stories.tsx, src/components/LogRow/ResmokeRow/ResmokeRow.stories.tsx, src/pages/LogView/LoadingPage/index.tsx, src/utils/string/index.ts, src/utils/string/string.test.ts
EVG-17542
This PR adds the JIRA formatting functionality to the JIRA button in the Details Overlay panel.
- Added tests in `string.test.ts`
- Added tests in `ButtonRow.test.tsx`
- I copy pasted it into a JIRA ticket (you can try it on EVG-17542 if you would like)
=> EVG-17542: Implement copy functionality for JIRA button

cypress/integration/ansiiLogs/ansii_logView.ts, cypress/integration/resmokeLogs/resmoke_logView.ts, src/components/LogWindow/index.tsx, src/context/LogContext/index.tsx
EVG-18235
ProcessedLogLines was not defined when we initially load the window so the scrollToLine would not work.
=> EVG-18235 Fix bug where scrollToLine would not work on load

scripts/deploy-production.js
EVG-17668
Needed to trim the ends of stdout since it adds a new line
=> EVG-17668 trim end of stdout

cypress/integration/ansiiLogs/ansii_highlighting.ts, src/context/LogContext/index.tsx
EVG-18347
Jump to the first matching line on search
=> EVG-18347 Jump to first search result on search

src/analytics/logWindow/useLogWindowAnalytics.ts, src/components/DetailsOverlay/ButtonRow/ButtonRow.test.tsx, src/components/DetailsOverlay/ButtonRow/index.tsx, src/components/FiltersDrawer/index.tsx, src/components/LogRow/BaseRow/index.tsx, src/components/SideBar/index.tsx
EVG-18369
Add analytics for bookmark usage.
Add tooltip for clearing bookmark
Update tooltip copy for jira copy button
=> EVG-18369 Add Bookmark usage analytics and improve usability

cypress/integration/externalLinks.ts, src/constants/externalURLTemplates.ts, src/pages/LogView/LoadingPage/index.tsx
EVG-18352
Remove references to spruce job logs page and point to legacy job logs
=> EVG-18352 Remove references to spruce job logs page

src/components/DetailsOverlay/__snapshots__/DetailsOverlay.stories.storyshot, src/components/FiltersDrawer/FilterGroup/index.tsx, src/components/PopoverButton/__snapshots__/PopoverButton.stories.storyshot, src/components/SearchBar/__snapshots__/SearchBar.stories.storyshot, src/storyshots.test.ts
EVG-18295
This PR removes the temporary workaround we were using to get snapshots to pass.
- No visual changes.
- Updated snapshots.
=> EVG-18295: Remove mock in storyshots.test.ts

cypress/integration/uploadedLogs/upload.ts, src/components/SearchBar/__snapshots__/SearchBar.stories.storyshot, src/components/SearchBar/index.tsx, src/pages/LogDrop/FileDropper.tsx
EVG-18492
This PR modifies the code in `FileDropper` to better adhere to the [documentation](https://react-dropzone.js.org/#section-opening-file-dialog-programmatically). I removed the `"Release to upload"` prompt because I couldn't get it to work with it, and I don't think it's really necessarily.
Also changed text input type to `"text"` to prevent the `"LeafyGreen recommends using SearchInput..."` warnings.
=> EVG-18492: Fix drag and drop finickiness

cypress/integration/ansiiLogs/ansii_filtering.ts, cypress/integration/resmokeLogs/resmoke_filtering.ts, src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/FilterGroup.test.tsx, src/components/SidePanel/NavGroup/FilterNavGroup/FilterGroup/index.tsx, src/components/SidePanel/NavGroup/FilterNavGroup/FilterNavGroup.test.tsx
EVG-18595
* Disables submitting an invalid filter. 
* Adds popup descriptions of filter nav icons.
* Auto focus on input when clicking edit.
Unit tests
=> EVG-18595 Improve edit filter functionality and side nav usability

cypress/integration/ansiiLogs/ansii_searching.ts, cypress/integration/resmokeLogs/resmoke_searching.ts, src/context/LogContext/state.ts
EVG-18655
Paginating query params no longer resets the search position
https://user-images.githubusercontent.com/4605522/214154737-e5a6b558-4721-42c9-beec-4e54964a5d19.mov
e2e tests
=> EVG-18655 Ensure search index does not reset when adding bookmarks

.evergreen.yml, .storybook/main.ts
EVG-18870
Utilize the changes introduced by @malikchaya2  in EVG-17334 to upload files to storybook
=> EVG-18870 Preserve directory structure of files uploaded to storybook

package.json, yarn.lock
=> EVG-18649 Update sidenav to v13

.evergreen.yml, scripts/prepare-shell.sh
EVG-18933
- Upgrade Ubuntu to 20.04 and MongoDB to 5.0
=> EVG-18933: Upgrade Ubuntu

src/components/LogPane/index.tsx, src/components/LogRow/RowRenderer/index.tsx
EVG-18958
This is an exploratory pr to see if lowering the Overscan count causes people to report less log jumpiness.  See linked ticket for more info
=> EVG-18958 Lower overscan count to 50

src/constants/logURLTemplates.ts
EVG-18867
Adds a comment describing why this enum does not follow typical enum naming conventions.
=> EVG-18667 Add comment to log type enum

LICENSE, docs/decisions/0003-migrating-to-react-virtuoso.md, package.json, yarn.lock
EVG-18987
Installs the react-virtuoso library and creates a WIP ADR that will be updated as this refactor progresses
Tested to see if I could import react-virtuoso without running into any vite problems.
=> EVG-18987 Install react-virtuoso and create ADR for virtualization migration

docs/decisions/0000-url-format.md, docs/decisions/0001-query-parameters.md, src/constants/logURLTemplates.ts
EVG-18986
Created 2 ADR's for Parsleys URL patterns and query params. These will serve as the documentation for how URL's are constructed in Parsley and should be updated if we decide to change anything. 
Tagging @bsamek  to ensure they are being used correctly and will render in the dev prod docs.
=> EVG-18986 Create ADR's for Parsley url and query params

src/components/ErrorBoundary/index.tsx
EVG-19094
This is a companion PR to evergreen-ci/spruce/pull/1721. It makes it so that we can tell from Bugsnag whether a user sees the error page or not.
- Tested manually on staging
=> EVG-19094: Add error page metadata in Bugsnag

.evergreen.yml, codegen.ts, package.json, scripts/check_codegen.sh, src/gql/generated/types.ts
EVG-19163
This PR creates the codegen config and adds the `check_codegen` task. Also cleaned up the YAML file a bit.
- `check_codegen` task should run and pass
=> EVG-19163: Configure GraphQL code generation

package.json, yarn.lock
=> EVG-19221 Remove @types/axios

.env-cmdrc.local.json, package.json, scripts/setup-credentials.js, src/context/GlobalProviders.tsx, src/gql/GQLProvider.tsx, src/utils/environmentVariables/index.ts, yarn.lock
EVG-19165
This PR creates the GQLProvider which is built off of the `ApolloProvider`. I did this first because I think it will unblock Sophie's work on writing the GQL queries.
(I was planning to do the user authentication first, but we can build authentication into the GQLProvider in a follow-up PR.)
=> EVG-19165: Create GQLProvider

.evergreen.yml
EVG-19222
On the last 5 tasks it took around 1 minute, i gave it 10x that to be safe.
=> EVG-19222 Abort if it takes over 10 minutes to start evergreen

README.md
=> EVG-19289 Update readme with 1password cred retrieval info

src/analytics/loadingPage/useLogDownloadAnalytics.ts
EVG-19318
Forgot to add this on my previous pr
=> EVG-19318 useAnalyticsRoot on useLogDropAnalytics

src/context/auth/index.tsx, src/gql/generated/types.ts, src/pages/index.tsx
EVG-19331
This PR updates some styles to prevent log lines from being cut off. Also adds basic error catching to the `checkLogin` function, which doesn't deauthenticate the user because I don't want users to lose their auth token due to random network errors. Depending on how often this happens we can explore adding retries in the future.
- Manually
=> EVG-19331: Fix style issue causing log lines to be cut off

src/components/ErrorBoundary/index.tsx, src/gql/generated/types.ts, src/gql/queries/get-user.graphql, src/gql/queries/index.ts, src/hooks/index.ts, src/hooks/useUser.ts, src/pages/index.tsx, src/utils/errorReporting/index.ts
EVG-19266
Fetch user ID and include it in BugSnag error reporting
=> EVG-19266: Log username with BugSnag errors

src/components/NavBar/index.tsx, src/constants/externalLinks.ts
=> EVG-19692 Update wiki link to point to pine

src/analytics/loadingPage/useLogDownloadAnalytics.ts, src/hooks/useLogDownloader/index.ts
EVG-19905
Trying to narrow down if a user is actually missing logs that should have been downloaded.
=> EVG-19905 Add analytics for incomplete log downloads

src/components/ShortcutModal/ShortcutModal.stories.tsx, src/components/ShortcutModal/__snapshots__/ShortcutModal.stories.storyshot, src/components/ShortcutModal/index.tsx
EVG-19911
This shortcut was missing from the shortcut modal
=> EVG-19911 Add apply filter shortcut to shortcut modal

src/components/LogRow/AnsiiRow/__snapshots__/AnsiiRow.stories.storyshot, src/components/LogRow/BaseRow/index.tsx, src/components/LogRow/ResmokeRow/__snapshots__/ResmokeRow.stories.storyshot, src/gql/generated/types.ts
EVG-19678
Very much a nit pr but add  1px of padding to the anchor icons so they don't appear pinned against the side nav.
Before:
After:
=> EVG-19678 Add slight padding to anchor icons

package.json, scripts/push-version.sh
EVG-19734
- Duplicates https://github.com/evergreen-ci/spruce/pull/1883
=> EVG-19734: Delay pushing git tags

README.md, package.json
EVG-20293
To help reduce some confusion around broken dependencies update the readme and introduce the `yarn clean` command
=> EVG-20293 Add yarn clean command and update readme

.storybook/preview.tsx, package.json, src/components/BookmarksBar/BookmarksBar.test.tsx, src/components/DetailsMenu/SearchRangeInput/SearchRangeInput.test.tsx, src/components/DetailsMenu/Toggles/CaseSensitiveToggle/CaseSensitiveToggle.test.tsx, src/components/DetailsMenu/Toggles/ExpandableRowsToggle/ExpandableRowsToggle.test.tsx, src/components/DetailsMenu/Toggles/FilterLogicToggle/FilterLogic.test.tsx, src/components/DetailsMenu/Toggles/PrettyPrintToggle/PrettyPrintToggle.test.tsx, src/components/DetailsMenu/Toggles/WrapToggle/WrapToggle.test.tsx, src/components/LogRow/BaseRow/Row.test.tsx, src/components/NavBar/UploadLink/UploadLink.test.tsx, src/components/ProjectFiltersModal/ProjectFiltersModal.test.tsx, src/components/SidePanel/NavGroup/FilterNavGroup/FilterNavGroup.test.tsx, src/components/SidePanel/NavGroup/HighlightNavGroup/HighlightNavGroup.test.tsx, src/context/LogContext/LogContext.test.tsx, src/context/auth/auth.test.tsx, src/gql/generated/types.ts, src/hooks/useFilterParam/useFilterParam.test.tsx, src/hooks/useHighlightParam/useHighlightParam.test.tsx, src/hooks/useQueryParam/useQueryParam.test.tsx, src/pages/Login.tsx, src/test_utils/index.tsx, yarn.lock
EVG-19102
- Implemented in Spruce in https://github.com/evergreen-ci/spruce/pull/1818
- In Storybook, use `createMemoryRouter` over <MemoryRouter />.
- Replace `<HistoryRouter>` instances with `<MemoryRouter>`
=> EVG-19102: Upgrade Router

src/context/toast/index.tsx, src/hooks/useLogDownloader/index.ts, src/hooks/useLogDownloader/useLogDownloader.test.ts
=> EVG-20581 Don't auto-dismiss log download incomplete toast

src/analytics/logWindow/useLogWindowAnalytics.ts, src/components/LogRow/BaseRow/index.tsx
EVG-20930
I noticed we weren't tracking how often people use the Shareline feature.
=> EVG-20930 Add analytics for share line usage

docs/03-Searching-and-filtering.md
- Update Parsley filter docs to point to Evergreen docs for configuring project-level filters
- Improve text hierarchy
=> Update filter docs

.github/dependabot.yml
Duplicates https://github.com/evergreen-ci/spruce/pull/2234
=> Dependabot: Add team as reviewer

src/components/styles/GlobalStyles.tsx
DEVPROD-1136
- Reduce tab size from 8 to 4 to improve log formatting
=> DEVPROD-1136: Reduce tab width

src/components/ErrorHandling/Sentry.tsx, src/gql/GQLProvider.tsx, src/gql/generated/types.ts, src/hooks/useLogDownloader/index.ts, src/utils/errorReporting/errorReporting.test.ts, src/utils/errorReporting/index.ts, src/utils/matchingLines/index.ts
DEVPROD-356
Implements the same as https://github.com/evergreen-ci/spruce/pull/2262
=> DEVPROD-356: Add Sentry grouping

.evergreen.yml
DEVPROD-5066
This one just had the typo (I think the file path is correct).
=> DEVPROD-5066: Fix errors in deploy script

jest.config.js, scripts/deploy/utils/git/tag/tag-utils.test.ts
Fixes DEVPROD-5132 (#500)
Duplicates https://github.com/evergreen-ci/spruce/pull/2292
Also start testing `scripts/` directory heh
=> DEVPROD-5132: Remove prefix from git tag test

scripts/deploy/deploy-production.ts, scripts/deploy/utils/git/tag/mock-tag-utils.ts, scripts/deploy/utils/git/tag/tag-utils.ts
DEVPROD-5788
Duplicates https://github.com/evergreen-ci/spruce/pull/2315
=> DEVPROD-5788: Set version when deploying
